language: python
python:
  - "3.9"

# Cache PlatformIO packages using Travis CI container-based infrastructure.
sudo: false
cache:
  directories:
    - "~/.platformio"
    - $HOME/.cache/pip

env:
  - PLATFORMIO_CI_SRC=examples/ESPCrashMonitorExample

install:
  - pip install -U platformio
  - platformio update
  - platformio lib -g update

script:
  - platformio ci --lib="." --board=huzzah

notifications:
  email:
    on_success: change
    on_failure: change